# Full Catalog of 100 Unique Executable SQL Queries for EnterpriseHub

QUERY_CATALOG = [
    # Basic SELECT & Filters (1-20)
    {"id": 1, "name": "Select All Employees", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT employee_id, first_name, last_name, email, salary FROM employees LIMIT 15;", "concept": "Projection & Selection", "tables": ["employees"], "explanation": "Retrieves employee columns."},
    {"id": 2, "name": "High Salary Filter (> $100k)", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM employees WHERE salary > 100000.00;", "concept": "WHERE Condition", "tables": ["employees"], "explanation": "Filters employees with salary over $100,000."},
    {"id": 3, "name": "Distinct Employee Genders", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT DISTINCT gender FROM employees;", "concept": "DISTINCT Keyword", "tables": ["employees"], "explanation": "Returns unique gender values."},
    {"id": 4, "name": "Hired Between 2020 and 2022", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM employees WHERE hire_date BETWEEN '2020-01-01' AND '2022-12-31';", "concept": "BETWEEN Operator", "tables": ["employees"], "explanation": "Selects employees hired between 2020 and 2022."},
    {"id": 5, "name": "Engineering & R&D Employees", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM employees WHERE department_id IN (2, 6);", "concept": "IN Operator", "tables": ["employees"], "explanation": "Filters employees in departments 2 and 6."},
    {"id": 6, "name": "Employees Not in Sales or HR", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM employees WHERE department_id NOT IN (3, 4);", "concept": "NOT IN Operator", "tables": ["employees"], "explanation": "Excludes Sales and HR departments."},
    {"id": 7, "name": "Emails Ending in enterprise.com", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM employees WHERE email LIKE '%@enterprise.com';", "concept": "LIKE Pattern Matching", "tables": ["employees"], "explanation": "Matches company email domain."},
    {"id": 8, "name": "Customers in New York or Chicago", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM customers WHERE city IN ('New York', 'Chicago');", "concept": "IN Clause", "tables": ["customers"], "explanation": "Filters customers by major cities."},
    {"id": 9, "name": "Products Price $500 - $2000", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM products WHERE price BETWEEN 500 AND 2000 ORDER BY price DESC;", "concept": "ORDER BY DESC", "tables": ["products"], "explanation": "Sorts mid-range products by price descending."},
    {"id": 10, "name": "Top 5 Highest Paid Employees", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT employee_id, first_name, last_name, salary FROM employees ORDER BY salary DESC LIMIT 5;", "concept": "LIMIT & ORDER BY", "tables": ["employees"], "explanation": "Finds top 5 highest earners."},
    {"id": 11, "name": "Phones Starting with 555-01", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM employees WHERE phone LIKE '555-01%';", "concept": "LIKE Wildcard", "tables": ["employees"], "explanation": "Prefix matching on phone numbers."},
    {"id": 12, "name": "High Budget Projects (> $300k)", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM projects WHERE budget > 300000 AND start_date >= '2022-01-01';", "concept": "AND Logic", "tables": ["projects"], "explanation": "Filters recent high-budget projects."},
    {"id": 13, "name": "Completed Orders by Amount", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM orders WHERE status = 'Completed' ORDER BY total_amount DESC;", "concept": "Filtered Ordering", "tables": ["orders"], "explanation": "Retrieves completed orders sorted by revenue."},
    {"id": 14, "name": "Products Low Stock (< 40 Units)", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM products WHERE stock_quantity < 40;", "concept": "Comparison Operator", "tables": ["products"], "explanation": "Identifies products needing replenishment."},
    {"id": 15, "name": "Books Published After 2015", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM books WHERE publication_year > 2015;", "concept": "Numeric Filtering", "tables": ["books"], "explanation": "Filters recent publication titles."},
    {"id": 16, "name": "Grade A Customers in New York", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM customers WHERE customer_grade = 'A' AND city = 'New York';", "concept": "Compound WHERE", "tables": ["customers"], "explanation": "Filters premium VIP customers in NY."},
    {"id": 17, "name": "Employees Without Manager", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM employees WHERE manager_id IS NULL;", "concept": "IS NULL Operator", "tables": ["employees"], "explanation": "Identifies top executive leadership."},
    {"id": 18, "name": "Orders Placed in March 2023", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT * FROM orders WHERE order_date BETWEEN '2023-03-01' AND '2023-03-31';", "concept": "Date Range Filter", "tables": ["orders"], "explanation": "Filters March 2023 transactions."},
    {"id": 19, "name": "Top 10 Cheapest Catalog Products", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT product_name, price FROM products ORDER BY price ASC LIMIT 10;", "concept": "Ascending Sorting", "tables": ["products"], "explanation": "Selects 10 lowest priced items."},
    {"id": 20, "name": "Paginated Employees Query", "category": "Basic SQL", "difficulty": "Level 1 (Beginner)", "sql": "SELECT employee_id, first_name, last_name FROM employees ORDER BY employee_id LIMIT 5 OFFSET 5;", "concept": "OFFSET Pagination", "tables": ["employees"], "explanation": "Fetches page 2 of employee listings."},

    # Aggregation & GROUP BY (21-35)
    {"id": 21, "name": "Total Payroll Expenditure", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT SUM(salary) AS total_payroll FROM employees;", "concept": "SUM() Function", "tables": ["employees"], "explanation": "Calculates total salary expense."},
    {"id": 22, "name": "Average Employee Salary", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT AVG(salary) AS avg_company_salary FROM employees;", "concept": "AVG() Function", "tables": ["employees"], "explanation": "Computes average salary."},
    {"id": 23, "name": "Min & Max Salary", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT MIN(salary) AS min_salary, MAX(salary) AS max_salary FROM employees;", "concept": "MIN() & MAX()", "tables": ["employees"], "explanation": "Finds salary range endpoints."},
    {"id": 24, "name": "Employee Count per Department", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT department_id, COUNT(*) AS emp_count FROM employees GROUP BY department_id;", "concept": "GROUP BY Clause", "tables": ["employees"], "explanation": "Counts workforce per department."},
    {"id": 25, "name": "Average Salary per Department", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT department_id, AVG(salary) AS avg_salary FROM employees GROUP BY department_id;", "concept": "Group Aggregation", "tables": ["employees"], "explanation": "Calculates average pay per department."},
    {"id": 26, "name": "Departments with >5 Employees", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT department_id, COUNT(*) AS emp_count FROM employees GROUP BY department_id HAVING COUNT(*) > 5;", "concept": "HAVING Filter", "tables": ["employees"], "explanation": "Filters grouped results by size."},
    {"id": 27, "name": "Lifetime Spent per Customer", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT customer_id, SUM(total_amount) AS lifetime_spent FROM orders GROUP BY customer_id;", "concept": "Customer Aggregation", "tables": ["orders"], "explanation": "Totals spending per customer."},
    {"id": 28, "name": "VIP Customers Spending > $30k", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT customer_id, SUM(total_amount) AS total_spent FROM orders GROUP BY customer_id HAVING SUM(total_amount) > 30000;", "concept": "HAVING Aggregation", "tables": ["orders"], "explanation": "Finds high-value spenders."},
    {"id": 29, "name": "Average Price per Category", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT category_id, AVG(price) AS avg_cat_price FROM products GROUP BY category_id;", "concept": "Category Average", "tables": ["products"], "explanation": "Averages product price by category."},
    {"id": 30, "name": "High-Value Product Categories", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT category_id, AVG(price) AS avg_price FROM products GROUP BY category_id HAVING AVG(price) > 1000;", "concept": "HAVING Price Threshold", "tables": ["products"], "explanation": "Filters premium category averages."},
    {"id": 31, "name": "Total Inventory per Warehouse", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT warehouse_id, SUM(quantity) AS total_stock FROM inventory GROUP BY warehouse_id;", "concept": "Warehouse Summary", "tables": ["inventory"], "explanation": "Totals stock per warehouse."},
    {"id": 32, "name": "Book Titles Count per Publisher", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT publisher_id, COUNT(*) AS book_count FROM books GROUP BY publisher_id;", "concept": "Publisher Aggregation", "tables": ["books"], "explanation": "Counts published books per publisher."},
    {"id": 33, "name": "Publishers with > 3 Books", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT publisher_id, COUNT(*) AS book_count FROM books GROUP BY publisher_id HAVING COUNT(*) > 3;", "concept": "HAVING Count Filter", "tables": ["books"], "explanation": "Filters major publishing houses."},
    {"id": 34, "name": "Salespersons Managing > 3 Accounts", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT salesperson_id, COUNT(*) AS customer_count FROM customers GROUP BY salesperson_id HAVING COUNT(*) > 3;", "concept": "Account Portfolio Size", "tables": ["customers"], "explanation": "Identifies busy sales representatives."},
    {"id": 35, "name": "Orders Breakdown by Status", "category": "Aggregation", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status;", "concept": "Status Breakdown", "tables": ["orders"], "explanation": "Summarizes order processing statuses."},

    # Joins (36-50)
    {"id": 36, "name": "Employee & Department Name", "category": "Joins", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT e.first_name, e.last_name, d.department_name FROM employees e INNER JOIN departments d ON e.department_id = d.department_id LIMIT 15;", "concept": "INNER JOIN", "tables": ["employees", "departments"], "explanation": "Joins employees to department names."},
    {"id": 37, "name": "All Employees & Department Name", "category": "Joins", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT e.first_name, e.last_name, d.department_name FROM employees e LEFT JOIN departments d ON e.department_id = d.department_id LIMIT 15;", "concept": "LEFT JOIN", "tables": ["employees", "departments"], "explanation": "Includes unassigned employees."},
    {"id": 38, "name": "Employee & Manager Self-Join", "category": "Joins", "difficulty": "Level 3 (Advanced)", "sql": "SELECT e.first_name AS employee, m.first_name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.employee_id LIMIT 15;", "concept": "SELF JOIN", "tables": ["employees"], "explanation": "Maps employees to their manager."},
    {"id": 39, "name": "Customer & Salesperson Assigned", "category": "Joins", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT c.customer_name, s.name AS salesperson_name FROM customers c LEFT JOIN salespersons s ON c.salesperson_id = s.salesperson_id LIMIT 15;", "concept": "Account Assignment Join", "tables": ["customers", "salespersons"], "explanation": "Joins customers to sales representatives."},
    {"id": 40, "name": "Orders with Customer Names", "category": "Joins", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT o.order_id, o.order_date, c.customer_name, o.total_amount FROM orders o JOIN customers c ON o.customer_id = c.customer_id LIMIT 15;", "concept": "Order Customer Join", "tables": ["orders", "customers"], "explanation": "Attaches customer details to orders."},
    {"id": 41, "name": "Products, Category & Supplier Multi-Join", "category": "Joins", "difficulty": "Level 3 (Advanced)", "sql": "SELECT p.product_name, c.category_name, s.supplier_name, p.price FROM products p JOIN categories c ON p.category_id = c.category_id JOIN suppliers s ON p.supplier_id = s.supplier_id LIMIT 15;", "concept": "3-Table Join", "tables": ["products", "categories", "suppliers"], "explanation": "Joins product, category, and supplier."},
    {"id": 42, "name": "Books & Publisher Name", "category": "Joins", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT b.title, p.publisher_name, b.publication_year FROM books b JOIN publishers p ON b.publisher_id = p.publisher_id LIMIT 15;", "concept": "Book Publisher Join", "tables": ["books", "publishers"], "explanation": "Links books to publishing houses."},
    {"id": 43, "name": "Books & Author Names", "category": "Joins", "difficulty": "Level 3 (Advanced)", "sql": "SELECT b.title, a.author_name FROM books b JOIN book_authors ba ON b.book_id = ba.book_id JOIN authors a ON ba.author_id = a.author_id LIMIT 15;", "concept": "Many-to-Many Join", "tables": ["books", "book_authors", "authors"], "explanation": "Resolves book-author relationship."},
    {"id": 44, "name": "Book Copies per Branch", "category": "Joins", "difficulty": "Level 3 (Advanced)", "sql": "SELECT b.title, lb.branch_name, bc.number_of_copies FROM book_copies bc JOIN books b ON bc.book_id = b.book_id JOIN library_branches lb ON bc.branch_id = lb.branch_id LIMIT 15;", "concept": "Branch Copies Join", "tables": ["book_copies", "books", "library_branches"], "explanation": "Shows book inventory by branch."},
    {"id": 45, "name": "Employee Hours Worked on Projects", "category": "Joins", "difficulty": "Level 3 (Advanced)", "sql": "SELECT e.first_name, e.last_name, p.project_name, ep.hours_worked FROM employee_projects ep JOIN employees e ON ep.employee_id = e.employee_id JOIN projects p ON ep.project_id = p.project_id LIMIT 15;", "concept": "Project Hours Join", "tables": ["employee_projects", "employees", "projects"], "explanation": "Logs employee time per project."},
    {"id": 46, "name": "Departments & Location Cities", "category": "Joins", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT d.department_name, l.city, l.country FROM departments d JOIN locations l ON d.location_id = l.location_id;", "concept": "Location Join", "tables": ["departments", "locations"], "explanation": "Maps departments to physical locations."},
    {"id": 47, "name": "Warehouses & Location Details", "category": "Joins", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT w.warehouse_name, l.city, l.state FROM warehouses w JOIN locations l ON w.location_id = l.location_id;", "concept": "Warehouse Location Join", "tables": ["warehouses", "locations"], "explanation": "Maps warehouses to cities."},
    {"id": 48, "name": "Category & Supplier Cross Join Matrix", "category": "Joins", "difficulty": "Level 3 (Advanced)", "sql": "SELECT c.category_name, s.supplier_name FROM categories c CROSS JOIN suppliers s LIMIT 15;", "concept": "CROSS JOIN", "tables": ["categories", "suppliers"], "explanation": "Generates Cartesian product matrix."},
    {"id": 49, "name": "Order Items Subtotal Calculation", "category": "Joins", "difficulty": "Level 3 (Advanced)", "sql": "SELECT oi.order_id, p.product_name, oi.quantity, oi.unit_price, (oi.quantity * oi.unit_price) AS subtotal FROM order_items oi JOIN products p ON oi.product_id = p.product_id LIMIT 15;", "concept": "Calculated Join Column", "tables": ["order_items", "products"], "explanation": "Computes item subtotal on the fly."},
    {"id": 50, "name": "Library Lending Record Full Details", "category": "Joins", "difficulty": "Level 3 (Advanced)", "sql": "SELECT bl.lending_id, m.member_name, b.title, lb.branch_name, bl.date_out FROM book_lending bl JOIN members m ON bl.member_id = m.member_id JOIN books b ON bl.book_id = b.book_id JOIN library_branches lb ON bl.branch_id = lb.branch_id LIMIT 15;", "concept": "4-Table Join", "tables": ["book_lending", "members", "books", "library_branches"], "explanation": "Full details for library loans."},

    # Subqueries (51-65)
    {"id": 51, "name": "Employees Earning Above Company Average", "category": "Subqueries", "difficulty": "Level 3 (Advanced)", "sql": "SELECT employee_id, first_name, last_name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);", "concept": "Scalar Subquery", "tables": ["employees"], "explanation": "Finds employees earning above company mean."},
    {"id": 52, "name": "Employee with Maximum Salary", "category": "Subqueries", "difficulty": "Level 3 (Advanced)", "sql": "SELECT * FROM employees WHERE salary = (SELECT MAX(salary) FROM employees);", "concept": "Single-Row Subquery", "tables": ["employees"], "explanation": "Finds highest overall earner."},
    {"id": 53, "name": "Employees in US Locations", "category": "Subqueries", "difficulty": "Level 3 (Advanced)", "sql": "SELECT * FROM employees WHERE department_id IN (SELECT department_id FROM departments WHERE location_id IN (SELECT location_id FROM locations WHERE country = 'USA'));", "concept": "Nested Multi-Row Subquery", "tables": ["employees", "departments", "locations"], "explanation": "Nested subqueries filtering by country."},
    {"id": 54, "name": "Employees Above Department Average", "category": "Subqueries", "difficulty": "Level 4 (Expert)", "sql": "SELECT e.employee_id, e.first_name, e.last_name, e.salary, e.department_id FROM employees e WHERE e.salary > (SELECT AVG(salary) FROM employees WHERE department_id = e.department_id);", "concept": "Correlated Subquery", "tables": ["employees"], "explanation": "Correlated comparison per department."},
    {"id": 55, "name": "Active Purchasing Customers (EXISTS)", "category": "Subqueries", "difficulty": "Level 3 (Advanced)", "sql": "SELECT c.customer_id, c.customer_name FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.customer_id);", "concept": "EXISTS Operator", "tables": ["customers", "orders"], "explanation": "Checks for presence of customer orders."},
    {"id": 56, "name": "Inactive Customers (NOT EXISTS)", "category": "Subqueries", "difficulty": "Level 3 (Advanced)", "sql": "SELECT c.customer_id, c.customer_name FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.customer_id);", "concept": "NOT EXISTS Operator", "tables": ["customers", "orders"], "explanation": "Finds customers who never ordered."},
    {"id": 57, "name": "Products Never Ordered", "category": "Subqueries", "difficulty": "Level 3 (Advanced)", "sql": "SELECT p.product_id, p.product_name FROM products p WHERE NOT EXISTS (SELECT 1 FROM order_items oi WHERE oi.product_id = p.product_id);", "concept": "Unsold Product Detection", "tables": ["products", "order_items"], "explanation": "Identifies products with zero sales."},
    {"id": 58, "name": "Employees Assigned to Projects", "category": "Subqueries", "difficulty": "Level 3 (Advanced)", "sql": "SELECT e.employee_id, e.first_name, e.last_name FROM employees e WHERE EXISTS (SELECT 1 FROM employee_projects ep WHERE ep.employee_id = e.employee_id);", "concept": "Project Assignment Check", "tables": ["employees", "employee_projects"], "explanation": "Filters active project staff."},
    {"id": 59, "name": "Unassigned Employees", "category": "Subqueries", "difficulty": "Level 3 (Advanced)", "sql": "SELECT e.employee_id, e.first_name, e.last_name FROM employees e WHERE NOT EXISTS (SELECT 1 FROM employee_projects ep WHERE ep.employee_id = e.employee_id);", "concept": "Unassigned Staff Filter", "tables": ["employees", "employee_projects"], "explanation": "Finds staff available for projects."},
    {"id": 60, "name": "Department with Highest Average Salary", "category": "Subqueries", "difficulty": "Level 4 (Expert)", "sql": "SELECT department_id, AVG(salary) FROM employees GROUP BY department_id ORDER BY AVG(salary) DESC LIMIT 1;", "concept": "Grouped Subquery Target", "tables": ["employees"], "explanation": "Finds highest paying department."},
    {"id": 61, "name": "Customers Spending Above Average", "category": "Subqueries", "difficulty": "Level 4 (Expert)", "sql": "SELECT customer_id, SUM(total_amount) FROM orders GROUP BY customer_id HAVING SUM(total_amount) > (SELECT AVG(total_amount) FROM orders);", "concept": "HAVING Subquery", "tables": ["orders"], "explanation": "Finds spenders exceeding average order."},
    {"id": 62, "name": "Prolific Authors Titles", "category": "Subqueries", "difficulty": "Level 4 (Expert)", "sql": "SELECT b.title FROM books b WHERE b.book_id IN (SELECT ba.book_id FROM book_authors ba WHERE ba.author_id IN (SELECT author_id FROM book_authors GROUP BY author_id HAVING COUNT(*) > 1));", "concept": "Multi-Level In Subquery", "tables": ["books", "book_authors"], "explanation": "Filters books by multi-author writers."},
    {"id": 63, "name": "Employees Earning More Than Manager", "category": "Subqueries", "difficulty": "Level 4 (Expert)", "sql": "SELECT e.first_name AS emp_name, e.salary AS emp_salary, m.first_name AS mgr_name, m.salary AS mgr_salary FROM employees e JOIN employees m ON e.manager_id = m.employee_id WHERE e.salary > m.salary;", "concept": "Manager Comparison Join", "tables": ["employees"], "explanation": "Finds employees out-earning manager."},
    {"id": 64, "name": "Second Highest Salary", "category": "Subqueries", "difficulty": "Level 4 (Expert)", "sql": "SELECT MAX(salary) AS second_highest FROM employees WHERE salary < (SELECT MAX(salary) FROM employees);", "concept": "Second Maximum Pattern", "tables": ["employees"], "explanation": "Classic interview 2nd highest query."},
    {"id": 65, "name": "Third Highest Salary Subquery", "category": "Subqueries", "difficulty": "Level 4 (Expert)", "sql": "SELECT MIN(salary) FROM (SELECT DISTINCT salary FROM employees ORDER BY salary DESC LIMIT 3) AS top3;", "concept": "Derived Table Subquery", "tables": ["employees"], "explanation": "Finds 3rd highest unique salary."},

    # Window Functions & Advanced (66-75)
    {"id": 66, "name": "Employee Overall Salary Rank", "category": "Advanced Window Functions", "difficulty": "Level 4 (Expert)", "sql": "SELECT employee_id, first_name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) AS salary_rank FROM employees LIMIT 15;", "concept": "ROW_NUMBER()", "tables": ["employees"], "explanation": "Sequential rank across company."},
    {"id": 67, "name": "Salary Rank Within Department", "category": "Advanced Window Functions", "difficulty": "Level 4 (Expert)", "sql": "SELECT employee_id, first_name, department_id, salary, RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS dept_salary_rank FROM employees LIMIT 15;", "concept": "RANK() OVER (PARTITION BY)", "tables": ["employees"], "explanation": "Ranks salaries inside each department."},
    {"id": 68, "name": "Dense Rank Within Department", "category": "Advanced Window Functions", "difficulty": "Level 4 (Expert)", "sql": "SELECT employee_id, first_name, department_id, salary, DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS dense_rank FROM employees LIMIT 15;", "concept": "DENSE_RANK()", "tables": ["employees"], "explanation": "Dense rank without gaps."},
    {"id": 69, "name": "Top 3 Highest Paid per Department (CTE)", "category": "Advanced Window Functions", "difficulty": "Level 5 (Mastery)", "sql": "WITH RankedEmps AS (SELECT employee_id, first_name, department_id, salary, DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) as rk FROM employees) SELECT * FROM RankedEmps WHERE rk <= 3;", "concept": "CTE & DENSE_RANK()", "tables": ["employees"], "explanation": "Filters top 3 earners per department."},
    {"id": 70, "name": "Running Total Sales Cumulative", "category": "Advanced Window Functions", "difficulty": "Level 4 (Expert)", "sql": "SELECT order_id, order_date, total_amount, SUM(total_amount) OVER (ORDER BY order_date) AS running_total FROM orders LIMIT 15;", "concept": "SUM() OVER (ORDER BY)", "tables": ["orders"], "explanation": "Computes cumulative sales volume."},
    {"id": 71, "name": "Previous Order Amount (LAG)", "category": "Advanced Window Functions", "difficulty": "Level 4 (Expert)", "sql": "SELECT order_id, customer_id, order_date, total_amount, LAG(total_amount, 1) OVER (PARTITION BY customer_id ORDER BY order_date) AS previous_order_amount FROM orders LIMIT 15;", "concept": "LAG() Window Function", "tables": ["orders"], "explanation": "Retrieves previous order amount."},
    {"id": 72, "name": "Next Order Amount (LEAD)", "category": "Advanced Window Functions", "difficulty": "Level 4 (Expert)", "sql": "SELECT order_id, customer_id, order_date, total_amount, LEAD(total_amount, 1) OVER (PARTITION BY customer_id ORDER BY order_date) AS next_order_amount FROM orders LIMIT 15;", "concept": "LEAD() Window Function", "tables": ["orders"], "explanation": "Peeks at next order amount."},
    {"id": 73, "name": "Order Amount Change vs Previous", "category": "Advanced Window Functions", "difficulty": "Level 4 (Expert)", "sql": "SELECT order_id, customer_id, total_amount, total_amount - LAG(total_amount, 1, total_amount) OVER (PARTITION BY customer_id ORDER BY order_date) AS diff_from_prev FROM orders LIMIT 15;", "concept": "LAG() Variance", "tables": ["orders"], "explanation": "Calculates variance vs prior order."},
    {"id": 74, "name": "Salary Comparison to Dept Average", "category": "Advanced Window Functions", "difficulty": "Level 4 (Expert)", "sql": "SELECT employee_id, first_name, salary, department_id, AVG(salary) OVER (PARTITION BY department_id) AS dept_avg_salary FROM employees LIMIT 15;", "concept": "Windowed Aggregation", "tables": ["employees"], "explanation": "Displays employee pay alongside department mean."},
    {"id": 75, "name": "Salary Percentile Rank", "category": "Advanced Window Functions", "difficulty": "Level 4 (Expert)", "sql": "SELECT employee_id, first_name, salary, PERCENT_RANK() OVER (ORDER BY salary) AS salary_percentile FROM employees LIMIT 15;", "concept": "PERCENT_RANK()", "tables": ["employees"], "explanation": "Calculates relative salary percentile."},

    # CASE & Functions (76-90)
    {"id": 76, "name": "Employee & Customer Cities UNION", "category": "CASE & Functions", "difficulty": "Level 3 (Advanced)", "sql": "SELECT city FROM locations UNION SELECT city FROM customers;", "concept": "UNION Operator", "tables": ["locations", "customers"], "explanation": "Combines distinct city lists."},
    {"id": 77, "name": "Customer & Supplier Cities UNION ALL", "category": "CASE & Functions", "difficulty": "Level 3 (Advanced)", "sql": "SELECT city FROM customers UNION ALL SELECT city FROM suppliers;", "concept": "UNION ALL Operator", "tables": ["customers", "suppliers"], "explanation": "Combines cities including duplicates."},
    {"id": 78, "name": "Employee Salary Tier Classification", "category": "CASE & Functions", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT first_name, salary, CASE WHEN salary >= 120000 THEN 'Executive' WHEN salary >= 80000 THEN 'Senior' ELSE 'Mid/Junior' END AS salary_tier FROM employees LIMIT 15;", "concept": "CASE WHEN", "tables": ["employees"], "explanation": "Classifies salary ranges."},
    {"id": 79, "name": "Customer VIP Grade Mapping", "category": "CASE & Functions", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT customer_name, customer_grade, CASE customer_grade WHEN 'A' THEN 'VIP Platinum' WHEN 'B' THEN 'Gold Preferred' ELSE 'Standard' END AS tier_name FROM customers LIMIT 15;", "concept": "CASE Value Mapping", "tables": ["customers"], "explanation": "Maps grade letters to descriptive names."},
    {"id": 80, "name": "Product Stock Status Indicator", "category": "CASE & Functions", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT product_name, stock_quantity, CASE WHEN stock_quantity = 0 THEN 'Out of Stock' WHEN stock_quantity < 30 THEN 'Low Stock' ELSE 'Sufficient' END AS stock_status FROM products LIMIT 15;", "concept": "Stock Status Logic", "tables": ["products"], "explanation": "Flags inventory warning states."},
    {"id": 81, "name": "Formatted Full Name & Email", "category": "CASE & Functions", "difficulty": "Level 1 (Beginner)", "sql": "SELECT (first_name || ' ' || last_name) AS full_name, LOWER(email) AS clean_email FROM employees LIMIT 15;", "concept": "String Concatenation", "tables": ["employees"], "explanation": "Concatenates name parts."},
    {"id": 82, "name": "Upper Case Product & Title Length", "category": "CASE & Functions", "difficulty": "Level 1 (Beginner)", "sql": "SELECT UPPER(product_name), LENGTH(product_name) AS char_count FROM products LIMIT 15;", "concept": "UPPER() & LENGTH()", "tables": ["products"], "explanation": "Applies text formatting functions."},
    {"id": 83, "name": "Extract Email Domain Substring", "category": "CASE & Functions", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT email, SUBSTR(email, INSTR(email, '@') + 1) AS domain FROM employees LIMIT 15;", "concept": "SUBSTR & INSTR", "tables": ["employees"], "explanation": "Parses domain name from email."},
    {"id": 84, "name": "Employee Hire Year Extraction", "category": "CASE & Functions", "difficulty": "Level 1 (Beginner)", "sql": "SELECT first_name, hire_date, STRFTIME('%Y', hire_date) AS hire_year FROM employees LIMIT 15;", "concept": "Date Format Function", "tables": ["employees"], "explanation": "Extracts year from date."},
    {"id": 85, "name": "Order Year & Month Extract", "category": "CASE & Functions", "difficulty": "Level 1 (Beginner)", "sql": "SELECT order_id, STRFTIME('%Y', order_date) AS order_year, STRFTIME('%m', order_date) AS order_month FROM orders LIMIT 15;", "concept": "Date Part Extraction", "tables": ["orders"], "explanation": "Extracts year and month."},
    {"id": 86, "name": "Price Rounding Functions", "category": "CASE & Functions", "difficulty": "Level 1 (Beginner)", "sql": "SELECT product_name, price, ROUND(price, 0) AS rounded_price FROM products LIMIT 15;", "concept": "ROUND() Function", "tables": ["products"], "explanation": "Rounds price to nearest integer."},
    {"id": 87, "name": "Payment Due Date (+14 Days)", "category": "CASE & Functions", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT order_id, order_date, DATE(order_date, '+14 days') AS payment_due_date FROM orders LIMIT 15;", "concept": "Date Arithmetic", "tables": ["orders"], "explanation": "Adds 14 days to order date."},
    {"id": 88, "name": "Overdue Library Loans Filter", "category": "CASE & Functions", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT * FROM book_lending WHERE date_returned IS NULL AND due_date < DATE('now');", "concept": "Overdue Logic Filter", "tables": ["book_lending"], "explanation": "Finds unreturned overdue books."},
    {"id": 89, "name": "Completed Projects Duration", "category": "CASE & Functions", "difficulty": "Level 2 (Intermediate)", "sql": "SELECT project_name, start_date, end_date FROM projects WHERE end_date IS NOT NULL;", "concept": "Duration Filter", "tables": ["projects"], "explanation": "Selects closed project timelines."},
    {"id": 90, "name": "Monthly Sales Revenue Summary", "category": "CASE & Functions", "difficulty": "Level 3 (Advanced)", "sql": "SELECT STRFTIME('%Y-%m', order_date) AS month, SUM(total_amount) AS revenue FROM orders GROUP BY month ORDER BY month ASC;", "concept": "Monthly Revenue Rollup", "tables": ["orders"], "explanation": "Rolls up revenue by month."},

    # Advanced Interview Challenges (91-100)
    {"id": 91, "name": "Employees Working on ALL Dept #2 Projects", "category": "Advanced Relational Challenges", "difficulty": "Level 5 (Mastery / Interview)", "sql": "SELECT e.employee_id, e.first_name FROM employees e WHERE NOT EXISTS (SELECT p.project_id FROM projects p WHERE p.department_id = 2 AND NOT EXISTS (SELECT ep.project_id FROM employee_projects ep WHERE ep.employee_id = e.employee_id AND ep.project_id = p.project_id));", "concept": "Relational Division", "tables": ["employees", "projects", "employee_projects"], "explanation": "Relational division via double NOT EXISTS."},
    {"id": 92, "name": "Same City Customers Different Reps", "category": "Advanced Relational Challenges", "difficulty": "Level 4 (Expert)", "sql": "SELECT c1.customer_name AS customer1, c2.customer_name AS customer2, c1.city FROM customers c1 JOIN customers c2 ON c1.city = c2.city AND c1.customer_id < c2.customer_id WHERE c1.salesperson_id <> c2.salesperson_id;", "concept": "Pairwise Self-Join", "tables": ["customers"], "explanation": "Pairs customers in same city with different sales reps."},
    {"id": 93, "name": "Most Expensive Product per Category", "category": "Advanced Relational Challenges", "difficulty": "Level 5 (Mastery / Interview)", "sql": "SELECT p.product_name, p.category_id, p.price FROM products p WHERE p.price = (SELECT MAX(price) FROM products WHERE category_id = p.category_id);", "concept": "Correlated Category Max", "tables": ["products"], "explanation": "Finds highest price product per category."},
    {"id": 94, "name": "Third Highest Order Value", "category": "Advanced Relational Challenges", "difficulty": "Level 4 (Expert)", "sql": "SELECT DISTINCT total_amount FROM orders ORDER BY total_amount DESC LIMIT 1 OFFSET 2;", "concept": "Nth Highest Offset", "tables": ["orders"], "explanation": "Finds 3rd highest distinct order total."},
    {"id": 95, "name": "Top 3 Spenders by Customer Total", "category": "Advanced Relational Challenges", "difficulty": "Level 4 (Expert)", "sql": "SELECT c.customer_name, SUM(o.total_amount) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_id, c.customer_name ORDER BY total_spent DESC LIMIT 3;", "concept": "Top N Spenders", "tables": ["customers", "orders"], "explanation": "Ranks top 3 customers by revenue."},
    {"id": 96, "name": "Departments Without Projects", "category": "Advanced Relational Challenges", "difficulty": "Level 3 (Advanced)", "sql": "SELECT d.department_name FROM departments d LEFT JOIN projects p ON d.department_id = p.department_id WHERE p.project_id IS NULL;", "concept": "Anti-Join Pattern", "tables": ["departments", "projects"], "explanation": "Identifies departments without active projects."},
    {"id": 97, "name": "Projects Without Staff Assigned", "category": "Advanced Relational Challenges", "difficulty": "Level 3 (Advanced)", "sql": "SELECT p.project_name FROM projects p LEFT JOIN employee_projects ep ON p.project_id = ep.project_id WHERE ep.employee_id IS NULL;", "concept": "Unstaffed Project Check", "tables": ["projects", "employee_projects"], "explanation": "Finds projects with 0 staff members."},
    {"id": 98, "name": "Books Borrowed Above Mean Times", "category": "Advanced Relational Challenges", "difficulty": "Level 5 (Mastery / Interview)", "sql": "SELECT b.title, COUNT(bl.lending_id) AS borrow_count FROM books b JOIN book_lending bl ON b.book_id = bl.book_id GROUP BY b.book_id, b.title HAVING COUNT(bl.lending_id) > (SELECT COUNT(*)*1.0/COUNT(DISTINCT book_id) FROM book_lending);", "concept": "HAVING Subquery Average", "tables": ["books", "book_lending"], "explanation": "Finds books borrowed above average frequency."},
    {"id": 99, "name": "Authors Stocked Across Multiple Branches", "category": "Advanced Relational Challenges", "difficulty": "Level 5 (Mastery / Interview)", "sql": "SELECT a.author_name FROM authors a JOIN book_authors ba ON a.author_id = ba.author_id JOIN book_copies bc ON ba.book_id = bc.book_id GROUP BY a.author_id, a.author_name HAVING COUNT(DISTINCT bc.branch_id) > 1;", "concept": "Multi-Branch Author Reach", "tables": ["authors", "book_authors", "book_copies"], "explanation": "Finds authors whose books span multiple branches."},
    {"id": 100, "name": "Top 10% Salary Percentile Staff", "category": "Advanced Relational Challenges", "difficulty": "Level 5 (Mastery / Interview)", "sql": "SELECT employee_id, first_name, salary FROM (SELECT employee_id, first_name, salary, PERCENT_RANK() OVER (ORDER BY salary) AS pr FROM employees) AS ranked WHERE pr >= 0.90;", "concept": "PERCENT_RANK() Top Decile", "tables": ["employees"], "explanation": "Finds top 10% earners using PERCENT_RANK()."}
]

def get_all_queries(category=None, difficulty=None):
    result = QUERY_CATALOG
    if category and category != 'all':
        result = [q for q in result if q['category'].lower() == category.lower()]
    if difficulty and difficulty != 'all':
        result = [q for q in result if q['difficulty'].lower().startswith(difficulty.lower())]
    return result
